/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeEngine {
  constructor(width: number, height: number);
  processCommands(commandsJson: string): string;
  beginFrame(): void;
  commitFrame(): void;
  render(): string;
  renderFull(): string;
  setScreenMode(mode: string, footerHeight?: number | undefined | null): void;
  resize(width: number, height: number): void;
  nodeCount(): number;
  frameCount(): number;
  printTree(): string;
  validate(): boolean;
  shutdown(): void;
  setStyle(id: number, styleJson: string): void;
  setLayout(id: number, layoutJson: string): void;
  getNode(id: number): string;
  treeSummary(): string;
  root(): number;
  createNode(kind: string): number;
  appendChild(parent: number, child: number): boolean;
  removeNode(id: number): void;
  setText(id: number, text: string): void;
  hitGridCheck(x: number, y: number): number;
  hitGridIsDirty(): boolean;
  hitGridClearCurrent(): void;
  hitGridPushScissor(x: number, y: number, width: number, height: number): void;
  hitGridPopScissor(): void;
  hitGridAddCurrentClipped(x: number, y: number, width: number, height: number, id: number): void;
  hitGridDump(): string;
}

export declare class NativeEventBus {
  constructor();
  pushKey(key: string, ctrl: boolean, shift: boolean, alt: boolean): void;
  pushMouse(button: string, x: number, y: number): void;
  pushMouseMotion(x: number, y: number): void;
  pushPaste(text: string): void;
  pushResize(width: number, height: number, prevWidth: number, prevHeight: number): void;
  drain(): string;
  len(): number;
  isEmpty(): boolean;
  clear(): void;
}

export declare class NativeFocusManager {
  constructor();
  focus(id: number): boolean;
  blur(id: number): boolean;
  blurCurrent(): boolean;
  focused(): number;
  isFocused(id: number): boolean;
  traverse(direction: string): string;
  focusOrder(): Array<number>;
  clear(): void;
}

export declare class NativeHitGrid {
  constructor(width: number, height: number);
  resize(width: number, height: number): void;
  add(x: number, y: number, width: number, height: number, id: number): void;
  check(x: number, y: number): number;
  clearNext(): void;
  clearCurrent(): void;
  swap(): boolean;
  isDirty(): boolean;
  dimensions(): string;
  pushScissor(x: number, y: number, width: number, height: number): void;
  popScissor(): void;
  clearScissors(): void;
}

export declare class NativeKeymap {
  constructor();
  addBinding(
    layer: string,
    id: string,
    keys: string,
    command: string,
    description: string | undefined | null,
    priority: number,
  ): boolean;
  handleKey(key: string): string;
  hasPending(): boolean;
  clearPending(): void;
  setMode(mode: string): void;
  currentMode(): string;
  clearMode(): void;
  removeLayer(name: string): boolean;
  setChordTimeout(ms: number): void;
  chordTimeout(): number;
  pendingKeys(): Array<string>;
  activeBindings(): string;
  allBindings(): string;
  commandHistory(): Array<string>;
  clearHistory(): void;
  parseKey(keyStr: string): string;
  parseSequence(keyStr: string): Array<string>;
}

export declare class NativeScheduler {
  constructor(fps?: number | undefined | null);
  requestFrame(): void;
  beginFrame(): boolean;
  endFrame(): void;
  isIdle(): boolean;
  frameCount(): number;
  fps(): number;
  shouldRender(): boolean;
  requestRenderCoalesced(): void;
  requestRenderImmediate(): void;
  hasScheduledFrame(): boolean;
  isRendering(): boolean;
  beginRender(): void;
  endRender(): boolean;
}

export declare class NativeSpanFeed {
  constructor(options?: NativeSpanFeedOptions | undefined | null);
  write(data: Buffer): number;
  drainSpans(out: Buffer): number;
  close(): void;
  reset(): void;
  pendingSpans(): number;
  pendingBytes(): number;
  isClosed(): boolean;
  isBackpressured(): boolean;
  stats(): NativeSpanFeedStats;
  markConsumed(chunkIndex: number): void;
}

export declare class NativeTextEngine {
  constructor(text?: string | undefined | null);
  insertChar(ch: string): void;
  insertStr(text: string): void;
  deleteChar(): void;
  getText(): string;
  clear(): void;
  canUndo(): boolean;
  canRedo(): boolean;
  undo(): boolean;
  redo(): boolean;
  cursorLeft(): void;
  cursorRight(): void;
  cursorPosition(): number;
  setCursorPosition(pos: number): void;
  length(): number;
  lineCount(): number;
  isEmpty(): boolean;
  wordCount(): number;
}

export declare function createDarkTheme(): NapiTheme;

export declare function createLightTheme(): NapiTheme;

export declare function detectCapabilities(): TerminalCapabilities;

export declare function getVersion(): string;

export interface NapiTheme {
  name: string;
  colors: NapiThemeColors;
  spacing: NapiThemeSpacing;
  borders: NapiThemeBorders;
}

export interface NapiThemeBorders {
  style: string;
  fg: string;
}

export interface NapiThemeColors {
  background: string;
  surface: string;
  surfaceHigh: string;
  surfaceLow: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  text: string;
  textMuted: string;
  textDim: string;
  border: string;
  borderFocused: string;
  accent: string;
  accentForeground: string;
  error: string;
  warning: string;
  success: string;
  info: string;
  scrollbar: string;
  scrollbarThumb: string;
}

export interface NapiThemeSpacing {
  none: number;
  xxs: number;
  xs: number;
  sm: number;
  md: number;
  lg: number;
  xl: number;
  xxl: number;
}

export interface NativeSpanFeedOptions {
  chunkSize: number;
  initialChunks: number;
  maxBytes: number;
  growthPolicy: number;
  autoCommitOnFull: number;
  spanQueueCapacity: number;
}

export interface NativeSpanFeedStats {
  bytesWritten: number;
  spansCommitted: number;
  chunks: number;
  pendingSpans: number;
}

export interface TerminalCapabilities {
  brand: string;
  trueColor: boolean;
  kittyKeyboard: boolean;
  csiU: boolean;
  bracketedPaste: boolean;
  focusEvents: boolean;
  mouse: boolean;
  osc52: boolean;
  osc8: boolean;
  sync: boolean;
  sgrPixel: boolean;
  underlineColor: boolean;
  strikethrough: boolean;
  cursorStyle: boolean;
  alternateScroll: boolean;
  inlineImages: boolean;
  sixel: boolean;
  columns: number;
  rows: number;
}
