/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeEngine {
  constructor(width: number, height: number);
  processCommands(commandsJson: string): string;
  beginFrame(): void;
  commitFrame(): void;
  render(): string;
  renderFull(): string;
  resize(width: number, height: number): void;
  nodeCount(): number;
  frameCount(): number;
  printTree(): string;
  validate(): boolean;
  shutdown(): void;
}

export declare class NativeEventBus {
  constructor();
  pushKey(key: string, ctrl: boolean, shift: boolean, alt: boolean): void;
  pushMouse(button: string, x: number, y: number): void;
  pushResize(width: number, height: number, prevWidth: number, prevHeight: number): void;
  drain(): string;
  len(): number;
  isEmpty(): boolean;
  clear(): void;
}

export declare class NativeFocusManager {
  constructor();
  traverse(direction: string): string;
}

export declare class NativeKeymap {
  constructor();
  addBinding(
    layer: string,
    id: string,
    keys: string,
    command: string,
    description: string | undefined | null,
    priority: number,
  ): boolean;
  handleKey(key: string): string;
  hasPending(): boolean;
  clearPending(): void;
}

export declare class NativeScheduler {
  constructor(fps?: number | undefined | null);
  requestFrame(): void;
  beginFrame(): boolean;
  endFrame(): void;
  isIdle(): boolean;
  frameCount(): number;
}

export declare class NativeTextEngine {
  constructor(text?: string | undefined | null);
  insertChar(ch: string): void;
  insertStr(text: string): void;
  deleteChar(): void;
  getText(): string;
  clear(): void;
  canUndo(): boolean;
  canRedo(): boolean;
  undo(): boolean;
  redo(): boolean;
}

export declare function detectCapabilities(): TerminalCapabilities;

export declare function getVersion(): string;

export interface TerminalCapabilities {
  brand: string;
  trueColor: boolean;
  kittyKeyboard: boolean;
  csiU: boolean;
  bracketedPaste: boolean;
  focusEvents: boolean;
  mouse: boolean;
  osc52: boolean;
  osc8: boolean;
  sync: boolean;
  sgrPixel: boolean;
  underlineColor: boolean;
  strikethrough: boolean;
  cursorStyle: boolean;
  alternateScroll: boolean;
  inlineImages: boolean;
  sixel: boolean;
  columns: number;
  rows: number;
}
