/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NapiCapabilities {
  static detect(): NapiCapabilities;
  get brand(): string;
  get trueColor(): boolean;
  get kittyKeyboard(): boolean;
  get bracketedPaste(): boolean;
  get mouseSupport(): boolean;
  get osc52Clipboard(): boolean;
  get terminalSize(): Array<number>;
  get pixelSize(): Array<number>;
  get osc8(): boolean;
  get synchronizedOutput(): boolean;
  get underlineColor(): boolean;
  get strikethrough(): boolean;
  get cursorStyle(): boolean;
  get alternateScroll(): boolean;
  get kittyGraphics(): boolean;
  get sixel(): boolean;
  get itermImages(): boolean;
  get focusEvents(): boolean;
  get csiU(): boolean;
}

export declare class NapiEngine {
  constructor(width?: number | undefined | null, height?: number | undefined | null);
  /**
   * Process a batch of commands from JSON.
   * Returns a JSON string with { success: number, errors: string[], idMappings: {temp: real}[] }.
   */
  processCommands(commandsJson: string): string;
  /** Begin a new frame. */
  beginFrame(): void;
  /** Commit the current frame. */
  commitFrame(): void;
  /** Get the number of nodes in the tree. */
  nodeCount(): number;
  /** Get the current frame count. */
  frameCount(): string;
  /** Print the tree for debugging. */
  printTree(): string;
  /** Get a summary of the tree. */
  treeSummary(): string;
  /** Validate tree invariants. */
  validate(): boolean;
  /** Get the root node ID as a string. */
  root(): string;
  /** Get the arena generation (changes when nodes are allocated/freed). */
  generation(): string;
  /** Set text content on a node. */
  setText(id: number, text: string): void;
  /** Set style on a node. */
  setStyle(
    id: number,
    fg?: string | undefined | null,
    bg?: string | undefined | null,
    bold?: boolean | undefined | null,
    italic?: boolean | undefined | null,
    underline?: boolean | undefined | null,
  ): void;
  /** Create a node and return its ID. */
  createNode(kind: string): number;
  /** Append a child to a parent. */
  appendChild(parent: number, child: number): boolean;
  /** Remove a node and its descendants. */
  removeNode(id: number): void;
  /** Shutdown the engine. */
  shutdown(): void;
  /** Resize the renderer. */
  resize(width: number, height: number): void;
  /** Render the current tree. Returns ANSI output as a buffer. */
  render(): RenderResult;
  /** Render with full repaint. */
  renderFull(): RenderResult;
  /** Request a frame from the scheduler. */
  requestFrame(): void;
  /** Check if a frame should be rendered. */
  shouldRender(): string;
  /** Get renderer dimensions. */
  dimensions(): Array<number>;
  /** Enable or disable the entire post-processing pipeline. */
  setPostProcessingEnabled(enabled: boolean): void;
  /** Check if post-processing is enabled. */
  isPostProcessingEnabled(): boolean;
  /**
   * Add a color matrix pass.
   * matrix: 16 comma-separated f32 values (row-major 4x4 RGBA matrix)
   * enabled: whether the pass starts enabled
   */
  addColorMatrixPass(matrixStr: string, enabled?: boolean | undefined | null): void;
  /** Add a CRT effect pass. */
  addCrtPass(glow?: number | undefined | null, curvature?: number | undefined | null): void;
  /** Add a scanlines effect pass. */
  addScanlinesPass(
    intensity?: number | undefined | null,
    oddRows?: boolean | undefined | null,
  ): void;
  /** Add a vignette effect pass. */
  addVignettePass(
    strength?: number | undefined | null,
    radius?: number | undefined | null,
    falloff?: number | undefined | null,
  ): void;
  /** Add a noise effect pass. */
  addNoisePass(intensity?: number | undefined | null, seed?: number | undefined | null): void;
  /** Add a chromatic aberration effect pass. */
  addChromaticAberrationPass(strength?: number | undefined | null): void;
  /** Add a bloom effect pass. */
  addBloomPass(
    threshold?: number | undefined | null,
    strength?: number | undefined | null,
    radius?: number | undefined | null,
  ): void;
  /** Remove a render pass by name. */
  removeRenderPass(name: string): void;
  /** Enable or disable a render pass by name. */
  setPassEnabled(name: string, enabled: boolean): void;
  /** Check if a render pass is enabled. */
  isPassEnabled(name: string): boolean | null;
  /** Get the number of active render passes. */
  passCount(): number;
}

export declare class NapiEventBus {
  constructor();
  /** Push a key event. */
  pushKey(key: string, ctrl: boolean, shift: boolean, alt: boolean, targetId: number): void;
  /** Push a mouse event. */
  pushMouse(button: string, x: number, y: number, targetId: number): void;
  /** Push a mouse motion event. */
  pushMouseMotion(x: number, y: number, targetId: number): void;
  /** Push a paste event. */
  pushPaste(text: string, targetId: number): void;
  /** Push a resize event. */
  pushResize(width: number, height: number, prevWidth: number, prevHeight: number): void;
  /** Get the number of pending events. */
  len(): number;
  /** Check if the event bus is empty. */
  isEmpty(): boolean;
  /** Clear all events. */
  clear(): void;
  /** Drain all events as JSON. */
  drain(): string;
}

export declare class NapiFocusManager {
  constructor();
  /** Focus a node. Returns true if focus changed. */
  focus(id: number): boolean;
  /** Blur the currently focused node. */
  blurCurrent(): boolean;
  /** Blur a specific node. Returns true if the node was blurred. */
  blur(id: number): boolean;
  /** Get the currently focused node ID (0 if none). */
  focused(): number;
  /** Check if a specific node is focused. */
  isFocused(id: number): boolean;
  /** Traverse focus to next/previous node. Returns the newly focused node ID (0 if none). */
  traverse(direction: string): number;
  /** Get focus order list. */
  focusOrder(): Array<number>;
}

export declare class NapiKeymap {
  constructor();
  /** Add a binding to a specific layer with full command name support */
  addBinding(
    layer: string,
    id: string,
    keys: string,
    command: string,
    description: string | undefined | null,
    priority: number,
  ): boolean;
  /** Set the current mode for mode-conditional bindings */
  setMode(mode: string): void;
  /** Get the current mode */
  currentMode(): string | null;
  /** Clear the current mode */
  clearMode(): void;
  /** Remove a layer by name */
  removeLayer(name: string): boolean;
  /** Set chord timeout in ms */
  setChordTimeout(ms: number): void;
  /** Get chord timeout in ms */
  chordTimeout(): number;
  /** Handle a key string (e.g. "ctrl+c") and return the command if matched */
  handleKey(keyStr: string): string | null;
  /** Check if there's a pending chord sequence */
  hasPending(): boolean;
  /** Clear any pending chord sequence */
  clearPending(): void;
  /** Get formatted pending keys (for UI display) */
  pendingKeys(): Array<string>;
  /** Get active bindings for cheat sheet / UI display */
  activeBindings(): Array<BindingInfo>;
  /** Get all bindings (including disabled) */
  allBindings(): Array<BindingInfo>;
  /** Get command history */
  commandHistory(): Array<string>;
  /** Clear command history */
  clearHistory(): void;
  /** Parse a key string into its normalized form */
  parseKey(keyStr: string): string | null;
  /** Parse a key sequence string into normalized parts */
  parseSequence(keyStr: string): Array<string>;
}

export declare class NapiScheduler {
  constructor(fps?: number | undefined | null);
  /** Request a frame. */
  requestFrame(): void;
  /** Check if a frame is due. */
  shouldRender(): string;
  /** Begin a frame. */
  beginFrame(): boolean;
  /** End a frame. */
  endFrame(): void;
  /** Get frame count. */
  frameCount(): string;
  /** Get dropped frame count. */
  droppedFrames(): string;
  /** Get the current FPS. */
  fps(): string;
  /** Get the frame budget in milliseconds. */
  frameBudgetMs(): string;
  /** Check if the scheduler is idle. */
  isIdle(): boolean;
}

export declare class NapiTextEngine {
  constructor(text?: string | undefined | null);
  /** Insert a character at the cursor position. */
  insertChar(ch: string): void;
  /** Insert a string at the cursor position. */
  insertStr(text: string): void;
  /** Insert text at the cursor position (alias for insertStr for compatibility). */
  insertText(text: string): void;
  /** Delete the character before the cursor (backspace). */
  deleteChar(): void;
  /** Delete character after the cursor (forward delete). */
  deleteCharForward(): void;
  /** Delete the word before the cursor. */
  deleteWordBackward(): void;
  /** Delete the word after the cursor. */
  deleteWordForward(): void;
  /** Delete from cursor to start of line. */
  deleteLineBackward(): void;
  /** Delete from cursor to end of line. */
  deleteLineForward(): void;
  /** Move cursor left one character. */
  cursorLeft(): void;
  /** Move cursor right one character. */
  cursorRight(): void;
  /** Move cursor up one line. */
  cursorUp(): void;
  /** Move cursor down one line. */
  cursorDown(): void;
  /** Move cursor to start of the current line. */
  cursorLineStart(): void;
  /** Move cursor to end of the current line. */
  cursorLineEnd(): void;
  /** Insert text at a specific position. */
  insertAt(position: number, text: string): void;
  /** Delete a range of characters. Returns the deleted text. */
  deleteAt(position: number, length: number): string;
  /** Get the character at a position. */
  charAt(position: number): string;
  /** Get a substring of the text buffer. */
  substring(start: number, end: number): string;
  /** Replace all occurrences of a pattern with replacement. Returns number of replacements. */
  replaceAll(pattern: string, replacement: string, caseSensitive: boolean): number;
  /** Check if undo is available. */
  canUndo(): boolean;
  /** Check if redo is available. */
  canRedo(): boolean;
  /** Get the total length in characters. */
  length(): number;
  /** Get all lines as a string array. */
  lines(): Array<string>;
}

export interface BindingInfo {
  id: string;
  keys: string;
  command: string;
  description?: string;
  enabled: boolean;
  layer: string;
}

/** Detect terminal capabilities. */
export declare function detectCapabilities(): string;

/** Get the library version. */
export declare function getVersion(): string;

/**
 * Highlight source code using tree-sitter syntax highlighting.
 *
 * Returns a JSON array of lines, each line being an array of segments.
 * Each segment has `text`, `fg`, `bg`, `bold`, `italic`, `underline`, and `dim` fields.
 * Colors are hex strings like `"#ff7b72"` or named strings like `"red"`.
 */
export declare function highlightCode(code: string, language: string): string;

export interface RenderResult {
  outputData: Array<number>;
  width: number;
  height: number;
  dirtyRegionCount: number;
}
