/* auto-generated by NAPI-RS */

import { execSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

interface NativeBinding {
  NapiCapabilities: new () => object;
  NapiEngine: new (width?: number, height?: number) => object;
  NapiEventBus: new () => object;
  NapiFocusManager: new () => object;
  NapiKeymap: new () => object;
  NapiScheduler: new (fps?: number) => object;
  NapiTextEngine: new (text?: string) => object;
  detectCapabilities: () => string;
  getVersion: () => string;
  highlightCode: (code: string, language: string) => string;
}

let nativeBinding: NativeBinding | null = null;
const loadErrors: Error[] = [];

const isMusl = (): boolean => {
  if (process.platform !== "linux") {
    return false;
  }
  const libcEnv = process.env.BETTERTUI_LIBC;
  if (libcEnv === "musl") return true;
  if (libcEnv === "gnu") return false;

  const fromFilesystem = isMuslFromFilesystem();
  if (fromFilesystem !== null) return fromFilesystem;

  const fromReport = isMuslFromReport();
  if (fromReport !== null) return fromReport;

  const fromChildProcess = isMuslFromChildProcess();
  if (fromChildProcess !== null) return fromChildProcess;

  return false;
};

const isFileMusl = (f: string): boolean => f.includes("libc.musl-") || f.includes("ld-musl-");

const isMuslFromFilesystem = (): boolean | null => {
  try {
    return readFileSync("/usr/bin/ldd", "utf-8").includes("musl");
  } catch {
    return null;
  }
};

const isMuslFromReport = (): boolean | null => {
  const report = getProcessReport();
  if (!report) return null;
  if (report.header?.glibcVersionRuntime) return false;
  if (Array.isArray(report.sharedObjects) && report.sharedObjects.some(isFileMusl)) {
    return true;
  }
  return false;
};

const isMuslFromChildProcess = (): boolean | null => {
  try {
    return execSync("ldd --version", { encoding: "utf8" }).includes("musl");
  } catch {
    return false;
  }
};

interface ProcessReport {
  header?: { glibcVersionRuntime?: string };
  sharedObjects?: string[];
}

const getProcessReport = (): ProcessReport | null => {
  if (!process.report || typeof process.report.getReport !== "function") {
    return null;
  }
  try {
    process.report.excludeNetwork = true;
    return process.report.getReport() as ProcessReport;
  } catch {
    return null;
  }
};

function resolveNativeBinding(): NativeBinding | null {
  const platform = process.platform;
  const arch = process.arch;

  if (platform === "darwin") {
    if (arch === "x64") {
      return tryLoad([
        "@bettertui/core-darwin-x64",
        "./index.darwin-x64.node",
        "./bettertui_bindings.darwin-x64.node",
      ]);
    }
    if (arch === "arm64") {
      return tryLoad([
        "@bettertui/core-darwin-arm64",
        "./index.darwin-arm64.node",
        "./bettertui_bindings.darwin-arm64.node",
      ]);
    }
    loadErrors.push(new Error(`Unsupported architecture on macOS: ${arch}`));
    return null;
  }

  if (platform === "linux") {
    const musl = isMusl();
    const abi = musl ? "musl" : "gnu";

    if (arch === "x64") {
      return tryLoad([
        `@bettertui/core-linux-x64-${abi}`,
        `./index.linux-x64-${abi}.node`,
        `./bettertui_bindings.linux-x64-${abi}.node`,
      ]);
    }
    if (arch === "arm64") {
      return tryLoad([
        `@bettertui/core-linux-arm64-${abi}`,
        `./index.linux-arm64-${abi}.node`,
        `./bettertui_bindings.linux-arm64-${abi}.node`,
      ]);
    }
    loadErrors.push(new Error(`Unsupported architecture on Linux: ${arch}`));
    return null;
  }

  if (platform === "win32") {
    if (arch === "x64") {
      return tryLoad([
        "@bettertui/core-win32-x64",
        "./index.win32-x64.node",
        "./bettertui_bindings.win32-x64.node",
      ]);
    }
    if (arch === "arm64") {
      return tryLoad([
        "@bettertui/core-win32-arm64",
        "./index.win32-arm64.node",
        "./bettertui_bindings.win32-arm64.node",
      ]);
    }
    loadErrors.push(new Error(`Unsupported architecture on Windows: ${arch}`));
    return null;
  }

  loadErrors.push(new Error(`Unsupported platform: ${platform}-${arch}`));
  return null;
}

function tryLoad(candidates: string[]): NativeBinding | null {
  for (const candidate of candidates) {
    try {
      const mod = require(candidate);
      if (mod && typeof mod === "object") {
        if (typeof mod === "string") {
          const actualMod = require(mod);
          return actualMod;
        }
        return mod;
      }
    } catch (e) {
      loadErrors.push(e as Error);
    }
  }
  return null;
}

function loadNativeBinding(): NativeBinding {
  if (nativeBinding) return nativeBinding;

  nativeBinding = resolveNativeBinding();

  if (!nativeBinding) {
    if (loadErrors.length > 0) {
      const error = new Error(
        "Cannot find native binding. " +
          "npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). " +
          "Please try `npm i` again after removing both package-lock.json and node_modules directory.",
      );
      error.cause = loadErrors.reduce((err, cur) => {
        cur.cause = err;
        return cur;
      });
      throw error;
    }
    throw new Error("Failed to load native binding");
  }

  return nativeBinding;
}

const binding = loadNativeBinding();

export const NapiCapabilities = binding.NapiCapabilities;
export const NapiEngine = binding.NapiEngine;
export const NapiEventBus = binding.NapiEventBus;
export const NapiFocusManager = binding.NapiFocusManager;
export const NapiKeymap = binding.NapiKeymap;
export const NapiScheduler = binding.NapiScheduler;
export const NapiTextEngine = binding.NapiTextEngine;
export const detectCapabilities = binding.detectCapabilities;
export const getVersion = binding.getVersion;
export const highlightCode = binding.highlightCode;

export default binding;
