// Re-export all hooks and providers
export {
  Provider,
  useTheme,
  FocusProvider,
  useFocus,
  useKeyboard,
  TerminalProvider,
  useTerminal,
  useFrame,
  useClipboard,
  useAnimation,
} from "./hooks/index";

export type { Theme, ThemeColors, ThemeSpacing, ProviderProps } from "./hooks/index";

// Runtime (render + RuntimeProvider + useRuntime)
export { render, RuntimeProvider, useRuntime } from "./runtime";

// Re-export core types that users need
export type {
  Command,
  CommandBuffer,
  Instance,
  Runtime,
  KeyEvent,
  MouseEvent,
  MouseButton,
  ResizeEvent,
  PasteEvent,
  Style,
  ColorValue,
  BorderStyle,
  Rect,
  Point,
  Size,
} from "@bettertui/core";

// Re-export all components
export {
  Box,
  Flex,
  Grid,
  Stack,
  Spacer,
  Separator,
  Text,
  Heading,
  Label,
  Code,
  Blockquote,
  Button,
  Input,
  Textarea,
  Checkbox,
  Radio,
  Switch,
  Slider,
  Select,
  Combobox,
  Tabs,
  Accordion,
  Badge,
  Progress,
  Spinner,
  List,
  Tree,
  Table,
  DataTable,
  Tooltip,
  Modal,
  Popover,
  Dropdown,
  ContextMenu,
  Toast,
  StatusLine,
  Pane,
  Viewport,
  Calendar,
  Chart,
} from "./components";

export type {
  BoxProps,
  FlexProps,
  GridProps,
  StackProps,
  SpacerProps,
  SeparatorProps,
  TextProps,
  HeadingProps,
  LabelProps,
  CodeProps,
  BlockquoteProps,
  ButtonProps,
  InputProps,
  TextareaProps,
  CheckboxProps,
  RadioProps,
  SwitchProps,
  SliderProps,
  SelectProps,
  ComboboxProps,
  TabItem,
  TabsProps,
  AccordionProps,
  BadgeProps,
  ProgressProps,
  SpinnerProps,
  ListItem,
  ListProps,
  TreeNode,
  TreeProps,
  TableColumn,
  TableProps,
  DataTableProps,
  TooltipProps,
  ModalProps,
  PopoverProps,
  DropdownProps,
  ContextMenuProps,
  ToastProps,
  StatusLineProps,
  PaneProps,
  ViewportProps,
  CalendarProps,
  ChartProps,
} from "./components";
