// Re-export all hooks and providers
export {
  Provider,
  useTheme,
  FocusProvider,
  useFocus,
  useKeyboard,
  TerminalProvider,
  useTerminal,
  useResize,
  useFrame,
  useClipboard,
  useAnimation,
  useMouse,
  SelectionProvider,
  useSelection,
  CapabilitiesProvider,
  useCapabilities,
  useTimeline,
  easings,
  KeymapProvider,
  useKeymap,
  useKeymapEvent,
  useActiveBindings,
  usePendingSequence,
  useCommand,
  useKeyIntercept,
  useKeymapMode,
  Keymap,
} from "./hooks";

export type {
  Theme,
  ThemeColors,
  ThemeSpacing,
  ProviderProps,
  MouseState,
  EasingFunction,
  UseAnimationOptions,
  TimelineAnimation,
  Timeline,
  KeymapEvent,
  KeymapOptions,
  CommandHandler,
  BindingInfo,
} from "./hooks";

// Runtime (render + RuntimeProvider + useRuntime)
export { render, RuntimeProvider, useRuntime } from "./runtime";
export type { RenderHandle } from "./runtime";

// Re-export core types that users need
export type {
  Command,
  CommandBuffer,
  Instance,
  CommandRuntime,
  KeyEvent,
  MouseEvent,
  MouseButton,
  Style,
  ColorValue,
  BorderStyle,
  Rect,
  Point,
} from "@bettertui/core";

// Re-export layout types (re-exported from @bettertui/core which owns shared re-exports)
export type {
  FlexDirection as SharedFlexDirection,
  JustifyContent as SharedJustifyContent,
  AlignItems as SharedAlignItems,
  AlignSelf as SharedAlignSelf,
  Position as SharedPosition,
  Sizing as SharedSizing,
  Overflow as SharedOverflow,
  Padding as SharedPadding,
  Margin as SharedMargin,
  Inset as SharedInset,
  Gap as SharedGap,
  LayoutConstraints,
} from "@bettertui/core";

// Re-export all components
export {
  Box,
  Flex,
  Grid,
  Stack,
  Spacer,
  Separator,
  Text,
  Heading,
  Label,
  Code,
  Blockquote,
  Button,
  Input,
  Textarea,
  Checkbox,
  Radio,
  Switch,
  Slider,
  Select,
  Combobox,
  Tabs,
  Accordion,
  Badge,
  Progress,
  Spinner,
  List,
  Tree,
  Table,
  DataTable,
  Tooltip,
  Modal,
  Popover,
  Dropdown,
  ContextMenu,
  Toast,
  StatusLine,
  Pane,
  Viewport,
  Calendar,
  Chart,
  ScrollArea,
  Markdown,
  CodeBlock,
  Diff,
  PromptComposer,
  ChatView,
  StatusBar,
  ThinkingIndicator,
  Terminal,
  TerminalViewport,
  TerminalProcess,
  Slot,
  NerdFont,
} from "./components";

export type {
  FlexDirection,
  JustifyContent,
  AlignItems,
  AlignSelf,
  Position,
  Sizing,
  Padding,
  Margin,
  Inset,
  BoxProps,
  FlexProps,
  GridProps,
  StackProps,
  SpacerProps,
  SeparatorProps,
  TextProps,
  HeadingProps,
  LabelProps,
  CodeProps,
  BlockquoteProps,
  ButtonProps,
  InputProps,
  TextareaProps,
  CheckboxProps,
  RadioProps,
  SwitchProps,
  SliderProps,
  SelectProps,
  ComboboxProps,
  TabItem,
  TabsProps,
  AccordionProps,
  BadgeProps,
  ProgressProps,
  SpinnerProps,
  ListItem,
  ListProps,
  TreeNode,
  TreeProps,
  TableColumn,
  TableProps,
  DataTableProps,
  TooltipProps,
  ModalProps,
  PopoverProps,
  DropdownProps,
  ContextMenuProps,
  ToastProps,
  StatusLineProps,
  PaneProps,
  ViewportProps,
  CalendarProps,
  ChartProps,
  ScrollAreaProps,
  MarkdownProps,
  CodeBlockProps,
  DiffProps,
  PromptComposerProps,
  ChatMessage,
  ChatViewProps,
  StatusBarProps,
  ThinkingIndicatorProps,
  TerminalProps,
  TerminalViewportProps,
  TerminalProcessProps,
  SlotProps,
  NerdFontProps,
} from "./components";
export { renderToStringAsync, type TestRendererOptions } from "./testing";
